name: Build Gradle project
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }} - ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Create local.properties
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Run tests with Gradle Wrapper
        run: ./gradlew check

      - name: Run lint checks with Gradle Wrapper
        run: ./gradlew ktlintCheck

      - name: Run build with Gradle Wrapper
        run: ./gradlew build