name: Build Gradle project
on: push

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Create local.properties
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > ./local.properties
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.6.8
        id: todo
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests with Gradle Wrapper
        run: ./gradlew check
      - name: Run build with Gradle Wrapper
        run: ./gradlew build