name: Update Contributors in README

on:
  push:
    branches: [main]

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    # Grant write access for the workflow to update repo with Streeekers
    permissions:
      contents: write

    steps:
      - name: Update Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
